#ifndef ZLAY_BACKENDS_PLATFORM_WINRT_ZLAY_WINRT_CONFIG_H
#define ZLAY_BACKENDS_PLATFORM_WINRT_ZLAY_WINRT_CONFIG_H

#ifndef ZLAY_ENABLE_WINRT
#  define ZLAY_ENABLE_WINRT 0
#endif

#ifndef ZLAY_ENABLE_WINRT_MODERN_UI
#  define ZLAY_ENABLE_WINRT_MODERN_UI 0
#endif

#ifndef ZLAY_WINRT_DEFAULT_MODERN_FLAGS
#  define ZLAY_WINRT_DEFAULT_MODERN_FLAGS 0xFFFFFFFFu
#endif

#endif
