#ifndef ZLAY_RENDERER_CANVAS_ZLAY_CANVAS_COMMAND_H
#define ZLAY_RENDERER_CANVAS_ZLAY_CANVAS_COMMAND_H

#ifdef __cplusplus
extern "C" {
#endif

#include <zlay.h>

typedef enum ZLay_CanvasCommandType {
  ZLAY_CANVAS_COMMAND_NONE = 0,
  ZLAY_CANVAS_COMMAND_RECT,
  ZLAY_CANVAS_COMMAND_ROUNDED_RECT,
  ZLAY_CANVAS_COMMAND_LINE,
  ZLAY_CANVAS_COMMAND_PATH,
  ZLAY_CANVAS_COMMAND_TEXT,
  ZLAY_CANVAS_COMMAND_IMAGE,
  ZLAY_CANVAS_COMMAND_CLIP_BEGIN,
  ZLAY_CANVAS_COMMAND_CLIP_END,
  ZLAY_CANVAS_COMMAND_PUSH_TRANSFORM,
  ZLAY_CANVAS_COMMAND_POP_TRANSFORM,
  ZLAY_CANVAS_COMMAND_CUSTOM
} ZLay_CanvasCommandType;

ZLAY_API const char* ZLay_CanvasCommandTypeName(ZLay_CanvasCommandType type);

#ifdef __cplusplus
}
#endif

#endif
