#!/usr/bin/env python3

from __future__ import annotations

import argparse
from pathlib import Path


SHADERS = [
    ("ZLAY_SHADER_COMMON_ANTIALIASING_GLSL", "shader/common/antialiasing.glsl"),
    ("ZLAY_SHADER_COMMON_ANTIALIASING_HLSL", "shader/common/antialiasing.hlsl"),
    ("ZLAY_SHADER_COMMON_ANTIALIASING_SLANG", "shader/common/antialiasing.slang"),
    ("ZLAY_SHADER_COMMON_ANTIALIASING_WGSL", "shader/common/antialiasing.wgsl"),
    ("ZLAY_SHADER_GLSL_RECT_VERT", "shader/glsl/rect.vert.glsl"),
    ("ZLAY_SHADER_GLSL_RECT_FRAG", "shader/glsl/rect.frag.glsl"),
    ("ZLAY_SHADER_VULKAN_RECT_VERT", "shader/vulkan/rect.vert.glsl"),
    ("ZLAY_SHADER_VULKAN_RECT_FRAG", "shader/vulkan/rect.frag.glsl"),
    ("ZLAY_SHADER_WEBGL_RECT_VERT", "shader/webgl/rect.vert.glsl"),
    ("ZLAY_SHADER_WEBGL_RECT_FRAG", "shader/webgl/rect.frag.glsl"),
    ("ZLAY_SHADER_WGSL_RECT_VERT", "shader/wgsl/rect.vert.wgsl"),
    ("ZLAY_SHADER_WGSL_RECT_FRAG", "shader/wgsl/rect.frag.wgsl"),
    ("ZLAY_SHADER_HLSL_RECT_VERT", "shader/hlsl/rect.vert.hlsl"),
    ("ZLAY_SHADER_HLSL_RECT_FRAG", "shader/hlsl/rect.frag.hlsl"),
    ("ZLAY_SHADER_SLANG_RECT_VERT", "shader/slang/rect.vert.slang"),
    ("ZLAY_SHADER_SLANG_RECT_FRAG", "shader/slang/rect.frag.slang"),
]


def c_string_literal(text: str) -> str:
    escaped = text.replace("\\", "\\\\").replace('"', '\\"')
    escaped = escaped.replace("\r\n", "\n").replace("\r", "\n")
    return '"' + escaped.replace("\n", "\\n\"\n\"") + '"'


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Embed ZLay shader sources into a C include file.")
    parser.add_argument("--root", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    root = args.root.resolve()
    output = args.output.resolve()
    output.parent.mkdir(parents=True, exist_ok=True)

    lines: list[str] = [
        "/* Generated by scripts/embed_shaders.py. Do not edit manually. */",
        "",
    ]

    for symbol, relative_path in SHADERS:
        path = root / relative_path
        if not path.exists():
            raise SystemExit(f"Shader source not found: {path}")
        text = path.read_text(encoding="utf-8")
        lines.append(f"static const char {symbol}[] =")
        lines.append(c_string_literal(text) + ";")
        lines.append("")

    output.write_text("\n".join(lines), encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
