#ifndef ZLAY_OS_ZLAY_PLATFORM_H
#define ZLAY_OS_ZLAY_PLATFORM_H

#include <stdint.h>

#include <zlay.h>

#ifdef __cplusplus
extern "C" {
#endif

typedef enum ZLay_Platform {
  ZLAY_OS_PLATFORM_UNKNOWN = 0,
  ZLAY_OS_PLATFORM_WIN32 = 1,
  ZLAY_OS_PLATFORM_WINRT = 2,
  ZLAY_OS_PLATFORM_COCOA = 3,
  ZLAY_OS_PLATFORM_GTK = 4,
  ZLAY_OS_PLATFORM_X11 = 5,
  ZLAY_OS_PLATFORM_WAYLAND = 6,
  ZLAY_OS_PLATFORM_POSIX = 7,
  ZLAY_OS_PLATFORM_UNIX_BSD = 8,
  ZLAY_OS_PLATFORM_SOLARIS = 9,
  ZLAY_OS_PLATFORM_ANDROID = 10,
  ZLAY_OS_PLATFORM_IOS = 11,
  ZLAY_OS_PLATFORM_EMSCRIPTEN = 12
} ZLay_Platform;

typedef uint32_t ZLay_PlatformFlags;

#define ZLAY_OS_CURRENT_PLATFORM_FLAGS ((ZLay_PlatformFlags)ZLAY_CURRENT_PLATFORM)
#define ZLAY_OS_HAS_PLATFORM(platform) ZLAY_HAS_PLATFORM(platform)

#if ZLAY_IS_WINDOWS()
#define ZLAY_OS_HOST_PLATFORM ZLAY_OS_PLATFORM_WIN32
#elif ZLAY_IS_PLATFORM(ZLAY_PLATFORM_IOS) ||                                   \
    ZLAY_IS_PLATFORM(ZLAY_PLATFORM_TVOS) ||                                    \
    ZLAY_IS_PLATFORM(ZLAY_PLATFORM_WATCHOS) ||                                 \
    ZLAY_IS_PLATFORM(ZLAY_PLATFORM_VISIONOS)
#define ZLAY_OS_HOST_PLATFORM ZLAY_OS_PLATFORM_IOS
#elif ZLAY_IS_APPLE()
#define ZLAY_OS_HOST_PLATFORM ZLAY_OS_PLATFORM_COCOA
#elif ZLAY_IS_PLATFORM(ZLAY_PLATFORM_ANDROID)
#define ZLAY_OS_HOST_PLATFORM ZLAY_OS_PLATFORM_ANDROID
#elif ZLAY_IS_EMSCRIPTEN()
#define ZLAY_OS_HOST_PLATFORM ZLAY_OS_PLATFORM_EMSCRIPTEN
#elif ZLAY_IS_BSD()
#define ZLAY_OS_HOST_PLATFORM ZLAY_OS_PLATFORM_UNIX_BSD
#elif ZLAY_IS_PLATFORM(ZLAY_PLATFORM_SOLARIS)
#define ZLAY_OS_HOST_PLATFORM ZLAY_OS_PLATFORM_SOLARIS
#elif ZLAY_IS_UNIX()
#define ZLAY_OS_HOST_PLATFORM ZLAY_OS_PLATFORM_POSIX
#else
#define ZLAY_OS_HOST_PLATFORM ZLAY_OS_PLATFORM_UNKNOWN
#endif

#ifdef __cplusplus
}
#endif

#endif
