cmake_minimum_required(VERSION 3.24)

if (NOT DEFINED ZLAY_HEADER_PATH OR ZLAY_HEADER_PATH STREQUAL "")
  message(FATAL_ERROR "Set ZLAY_HEADER_PATH. Example: cmake -DZLAY_HEADER_PATH=zlay/zlay_buffer.h -DZLAY_HEADER_GUARD_STYLE=ifndef -P cmake/new_header.cmake")
endif()

if (NOT DEFINED ZLAY_HEADER_GUARD_STYLE OR ZLAY_HEADER_GUARD_STYLE STREQUAL "")
  set(ZLAY_HEADER_GUARD_STYLE "ifndef")
endif()

string(TOLOWER "${ZLAY_HEADER_GUARD_STYLE}" ZLAY_HEADER_GUARD_STYLE)
if (NOT ZLAY_HEADER_GUARD_STYLE MATCHES "^(ifndef|pragma_once|both)$")
  message(FATAL_ERROR "ZLAY_HEADER_GUARD_STYLE must be one of: ifndef, pragma_once, both")
endif()

if (NOT DEFINED ZLAY_HEADER_INCLUDE)
  set(ZLAY_HEADER_INCLUDE "zlay.h")
endif()

if (NOT DEFINED ZLAY_HEADER_EXTERN_C OR ZLAY_HEADER_EXTERN_C STREQUAL "")
  set(ZLAY_HEADER_EXTERN_C ON)
endif()

if (NOT DEFINED ZLAY_HEADER_OVERWRITE)
  set(ZLAY_HEADER_OVERWRITE OFF)
endif()

get_filename_component(ZLAY_PROJECT_ROOT "${CMAKE_CURRENT_LIST_DIR}/.." ABSOLUTE)

if (IS_ABSOLUTE "${ZLAY_HEADER_PATH}")
  set(ZLAY_HEADER_ABSOLUTE "${ZLAY_HEADER_PATH}")
else()
  set(ZLAY_HEADER_ABSOLUTE "${ZLAY_PROJECT_ROOT}/${ZLAY_HEADER_PATH}")
endif()

get_filename_component(ZLAY_HEADER_ABSOLUTE "${ZLAY_HEADER_ABSOLUTE}" ABSOLUTE)
file(RELATIVE_PATH ZLAY_HEADER_RELATIVE "${ZLAY_PROJECT_ROOT}" "${ZLAY_HEADER_ABSOLUTE}")

if (ZLAY_HEADER_RELATIVE MATCHES "^\\.\\.")
  message(FATAL_ERROR "ZLAY_HEADER_PATH must stay inside the project root: ${ZLAY_PROJECT_ROOT}")
endif()

if (EXISTS "${ZLAY_HEADER_ABSOLUTE}" AND NOT ZLAY_HEADER_OVERWRITE)
  file(SIZE "${ZLAY_HEADER_ABSOLUTE}" ZLAY_HEADER_EXISTING_SIZE)
  if (ZLAY_HEADER_EXISTING_SIZE GREATER 0)
    message(FATAL_ERROR "Header already exists and is not empty: ${ZLAY_HEADER_RELATIVE}. Pass -DZLAY_HEADER_OVERWRITE=ON to replace it.")
  endif()
endif()

set(ZLAY_HEADER_GUARD_SOURCE "${ZLAY_HEADER_RELATIVE}")
string(REGEX REPLACE "^zlay/" "" ZLAY_HEADER_GUARD_SOURCE "${ZLAY_HEADER_GUARD_SOURCE}")
string(REGEX REPLACE "[^A-Za-z0-9]" "_" ZLAY_HEADER_GUARD "${ZLAY_HEADER_GUARD_SOURCE}")
string(TOUPPER "${ZLAY_HEADER_GUARD}" ZLAY_HEADER_GUARD)
string(REGEX REPLACE "_+" "_" ZLAY_HEADER_GUARD "${ZLAY_HEADER_GUARD}")
string(REGEX REPLACE "^_+" "" ZLAY_HEADER_GUARD "${ZLAY_HEADER_GUARD}")
string(REGEX REPLACE "_+$" "" ZLAY_HEADER_GUARD "${ZLAY_HEADER_GUARD}")

if (NOT ZLAY_HEADER_GUARD MATCHES "_H$")
  string(APPEND ZLAY_HEADER_GUARD "_H")
endif()

if (NOT ZLAY_HEADER_GUARD MATCHES "^ZLAY_")
  set(ZLAY_HEADER_GUARD "ZLAY_${ZLAY_HEADER_GUARD}")
endif()

set(ZLAY_HEADER_PRAGMA_ONCE "")
set(ZLAY_HEADER_IFNDEF_OPEN "")
set(ZLAY_HEADER_IFNDEF_CLOSE "")

if (ZLAY_HEADER_GUARD_STYLE STREQUAL "pragma_once" OR ZLAY_HEADER_GUARD_STYLE STREQUAL "both")
  set(ZLAY_HEADER_PRAGMA_ONCE "#pragma once\n")
endif()

if (ZLAY_HEADER_GUARD_STYLE STREQUAL "ifndef" OR ZLAY_HEADER_GUARD_STYLE STREQUAL "both")
  set(ZLAY_HEADER_IFNDEF_OPEN "#ifndef ${ZLAY_HEADER_GUARD}\n#define ${ZLAY_HEADER_GUARD}\n\n")
  set(ZLAY_HEADER_IFNDEF_CLOSE "#endif\n")
endif()

set(ZLAY_HEADER_INCLUDE_BLOCK "")
if (NOT ZLAY_HEADER_INCLUDE STREQUAL "")
  if (ZLAY_HEADER_INCLUDE MATCHES "^[<\"].*[>\"]$")
    set(ZLAY_HEADER_INCLUDE_BLOCK "#include ${ZLAY_HEADER_INCLUDE}\n\n")
  else()
    set(ZLAY_HEADER_INCLUDE_BLOCK "#include <${ZLAY_HEADER_INCLUDE}>\n\n")
  endif()
endif()

set(ZLAY_HEADER_EXTERN_C_OPEN "")
set(ZLAY_HEADER_EXTERN_C_CLOSE "")
if (ZLAY_HEADER_EXTERN_C)
  set(ZLAY_HEADER_EXTERN_C_OPEN "#ifdef __cplusplus\nextern \"C\" {\n#endif\n\n")
  set(ZLAY_HEADER_EXTERN_C_CLOSE "#ifdef __cplusplus\n}\n#endif\n")
endif()

get_filename_component(ZLAY_HEADER_DIR "${ZLAY_HEADER_ABSOLUTE}" DIRECTORY)
file(MAKE_DIRECTORY "${ZLAY_HEADER_DIR}")
configure_file(
  "${CMAKE_CURRENT_LIST_DIR}/templates/zlay_header.h.in"
  "${ZLAY_HEADER_ABSOLUTE}"
  @ONLY
)

message(STATUS "Generated ${ZLAY_HEADER_RELATIVE} with ${ZLAY_HEADER_GUARD_STYLE} guard (${ZLAY_HEADER_GUARD})")
